#pragma once

inline const char* __fastcall GunIcon(const std::string weapon) {
	std::map<std::string, const char*> gunIcons = {
		{"ct_knife", "]"},
		{"t_knife", "["},
		{"deagle", "A"},
		{"elite", "B"},
		{"fiveseven", "C"},
		{"glock", "D"},
		{"revolver", "J"},
		{"p2000", "E"},
		{"p250", "F"},
		{"usp", "G"},
		{"tec9", "H"},
		{"cz75a", "I"},
		{"mac10", "K"},
		{"ump45", "L"},
		{"bizon", "M"},
		{"mp7", "N"},
		{"mp9", "R"},
		{"p90", "O"},
		{"galilar", "Q"},
		{"famas", "R"},
		{"m4a1_silencer", "T"},
		{"m4a1", "S"},
		{"aug", "U"},
		{"sg556", "V"},
		{"ak47", "W"},
		{"g3sg1", "X"},
		{"scar20", "Y"},
		{"awp", "Z"},
		{"ssg08", "a"},
		{"xm1014", "b"},
		{"sawedoff", "c"},
		{"mag7", "d"},
		{"nova", "e"},
		{"negev", "f"},
		{"m249", "g"},
		{"taser", "h"},
		{"flashbang", "i"},
		{"hegrenade", "j"},
		{"smokegrenade", "k"},
		{"molotov", "l"},
		{"decoy", "m"},
		{"incgrenade", "n"},
		{"c4", "o"},
		{"kit", "r"}
	};

	auto it = gunIcons.find(weapon);
	return (it != gunIcons.end()) ? it->second : "";
}

inline std::map<int, std::string> weaponNames = {
	{1, "deagle"},
	{2, "elite"},
	{3, "fiveseven"},
	{4, "glock"},
	{7, "ak47"},
	{8, "aug"},
	{9, "awp"},
	{10, "famas"},
	{11, "g3Sg1"},
	{13, "galilar"},
	{14, "m249"},
	{17, "mac10"},
	{19, "p90"},
	{23, "mp5sd"},
	{24, "ump45"},
	{25, "xm1014"},
	{26, "bizon"},
	{27, "mag7"},
	{28, "negev"},
	{29, "sawedoff"},
	{30, "tec9"},
	{31, "zeus"},
	{32, "p2000"},
	{33, "mp7"},
	{34, "mp9"},
	{35, "nova"},
	{36, "p250"},
	{38, "scar20"},
	{39, "sg556"},
	{40, "ssg08"},
	{42, "ct_knife"},
	{43, "flashbang"},
	{44, "hegrenade"},
	{45, "smokegrenade"},
	{46, "molotov"},
	{47, "decoy"},
	{48, "incgrenade"},
	{49, "c4"},
	{16, "m4a1"},
	{61, "usp"},
	{60, "m4a1_silencer"},
	{63, "cz75a"},
	{64, "revolver"},
	{59, "t_knife"}
};

inline std::string __fastcall GetWeaponName(int weaponID) {
	auto it = weaponNames.find(weaponID);
	if (it != weaponNames.end()) {
		return it->second;
	}
	return "Weapon_None";
}

enum class e_weapon_type : uint32_t
{
	knife,
	pistol,
	submachinegun,
	rifle,
	shotgun,
	sniper_rifle,
	machinegun,
	c4,
	taser,
	grenade,
	equipment,
	stackableitem,
	fists,
	breachcharge,
	bumpmine,
	tablet,
	melee,
	shield,
	zone_repulsor,
	unknown
};

enum ItemDefinitionIndex {
	weapon_deagle = 1,
	weapon_elite = 2,
	weapon_fiveseven = 3,
	weapon_glock = 4,
	weapon_ak47 = 7,
	weapon_aug = 8,
	weapon_awp = 9,
	weapon_famas = 10,
	weapon_g3sg1 = 11,
	weapon_galilar = 13,
	weapon_m249 = 14,
	weapon_m4a1 = 16,
	weapon_mac10 = 17,
	weapon_p90 = 19,
	weapon_ump = 24,
	weapon_xm1014 = 25,
	weapon_bizon = 26,
	weapon_mag7 = 27,
	weapon_negev = 28,
	weapon_sawedoff = 29,
	weapon_tec9 = 30,
	weapon_taser = 31,
	weapon_hkp2000 = 32,
	weapon_mp7 = 33,
	weapon_mp9 = 34,
	weapon_nova = 35,
	weapon_p250 = 36,
	weapon_scar20 = 38,
	weapon_sg556 = 39,
	weapon_ssg08 = 40,
	weapon_knife = 42,
	weapon_flashbang = 43,
	weapon_hegrenade = 44,
	weapon_smokegrenade = 45,
	weapon_molotov = 46,
	weapon_decoy = 47,
	weapon_incgrenade = 48,
	weapon_c4 = 49,
	weapon_knife_t = 59,
	weapon_m4a1_silencer = 60,
	weapon_usp_silencer = 61,
	weapon_cz75a = 63,
	weapon_revolver = 64,
	weapon_bayonet = 500,
	weapon_knife_flip = 505,
	weapon_knife_gut = 506,
	weapon_knife_karambit = 507,
	weapon_knife_m9_bayonet = 508,
	weapon_knife_tactical = 509,
	weapon_knife_falchion = 512,
	weapon_knife_survival_bowie = 514,
	weapon_knife_butterfly = 515,
	weapon_knife_push = 516
};
